### ISSUE TITLE
[THEME] tabs.ultimate-guitar.com

### ISSUE THREAD

**Issue by jondmarien** [sameerasw/my-internet#1590]
Please add a theme for tabs.ultimate-guitar.com

**Tried forcing:** YES
**Requires account:** NO

---

*This request was generated automatically from the Zen Internet extension.*

**Comment by sameerasw** [comment]
Done, Theme added/ updated. Please re-fetch your styles in a short while :) 

<img width="742" height="1230" alt="Image" src="https://github.com/user-attachments/assets/e1e4c40d-c7b5-4de3-bfe2-3c7d7be2bc2b" />

[![Build Status](https://img.shields.io/endpoint.svg?url=https%3A%2F%2Factions-badge.atrox.dev%2Fsameerasw%2Fmy-internet%2Fbadge%3Fref%3Dmain&style=for-the-badge)](https://actions-badge.atrox.dev/sameerasw/my-internet/goto?ref=main)

**Comment by jondmarien** [comment]
Hello, sorry to re-open/comment this --

I refetched the latest styles a few times; and even restarted zen browser, but the extension does not realize there is a theme for that site? See pictures.

<img width="348" height="296" alt="Image" src="https://github.com/user-attachments/assets/40c9d561-108b-4e29-8d19-59c87e57158f" />

<img width="343" height="587" alt="Image" src="https://github.com/user-attachments/assets/16fad730-f0f3-4a03-84a9-976fa1fd88e2" />

i went to this link: `tabs.ultimate-guitar.com`.

**Comment by jondmarien** [comment]
ah, let me update the extension and try again. is there a setting for auto updates?

**Comment by jondmarien** [comment]
Still the same, even after the update. :( 

Let me know your recommendations!

**Comment by sameerasw** [comment]
Ahh I see the issue, the tabs. prefix was not necessary. I will fix and update the style soon but might take a while for the style to get updated as currently github servers are having issues.

**Comment by sameerasw** [comment]
Done, re-fetch your styles in a short while :) 

<img width="377" alt="CleanShot 2025-03-08 at 10  02 30@2x" src="https://github.com/user-attachments/assets/bfd0a9c9-ede2-4059-aa30-8d574d42b795" />

[![Build Status](https://img.shields.io/endpoint.svg?url=https%3A%2F%2Factions-badge.atrox.dev%2Fsameerasw%2Fmy-internet%2Fbadge%3Fref%3Dmain&style=for-the-badge)](https://actions-badge.atrox.dev/sameerasw/my-internet/goto?ref=main)

**Comment by jondmarien** [comment]
ah, thank you!
