### ISSUE TITLE
[THEME] dev.azure.com

### ISSUE THREAD

**Issue by 0qln** [sameerasw/my-internet#842]
Please add a theme for dev.azure.com

**Comment by sameerasw** [comment]
I do not have a login for this website so contributions are welcome. :)

Meanwhile, try forcing the theme. You can use the new "force website to be themed" feature to get it transparent with darkreader support if needed. these themes can be experimental. If the website still fails to be usable, report it back please :)

Reference: 
https://github.com/sameerasw/zeninternet/issues/4

> Make sure your add-on is updated to 1.4.0+ and enable forcing.
<img width="395" alt="CleanShot 2025-03-05 at 7  02 15@2x" src="https://github.com/user-attachments/assets/9535f4a4-2639-4786-a693-962edb537a78" />

**Comment by 0qln** [comment]
### Quick info for anyone looking for the state of a theme for dev.azure.com:

I would love to contribute the theme for site, however, I am currently low on time and will not be able to start until Sunday.

If anyone else wants to do this instead, you're welcome to; please leave a message here in that case, such that we avoid duplicate work! :)

**Comment by 0qln** [comment]
@sameerasw 

It looks like the website uses iframes to display extensions:

![Image](https://github.com/user-attachments/assets/84a132d4-57fd-4f98-bae1-542cc4fd94f2)

These iframes do not inherit the css rules of the outer html. Trying to target the iframes `src` with another css file does also not work:

`planning-poker-azure-prod.firebaseapp.com.css`:
```css
/* transparency */
#root {
    display: none;
}
```

Looking at the [`content-script.js`](https://github.com/sameerasw/zeninternet/blob/master/content-script.js)
```js
// Listen for messages from background script
  browser.runtime.onMessage.addListener((message) => {
    if (message.action === "applyStyles") {
      updateStyles(message.css);
      return Promise.resolve({ success: true });
    }
    return false;
  });
```

, I would expect that Firefox also notifies your extension when iframes apply their styles, right?

Maybe I am missing something... do you know of a site that had a similar case, such that I can use it as reference?

**Comment by sameerasw** [comment]
> [@sameerasw](https://github.com/sameerasw)
> 
> It looks like the website uses iframes to display extensions:
> 
> ![Image](https://github.com/user-attachments/assets/84a132d4-57fd-4f98-bae1-542cc4fd94f2)
> 
> These iframes do not inherit the css rules of the outer html. Trying to target the iframes `src` with another css file does also not work:
> 
> `planning-poker-azure-prod.firebaseapp.com.css`:
> 
> /* transparency */
> #root {
>     display: none;
> }
> 
> Looking at the [`content-script.js`](https://github.com/sameerasw/zeninternet/blob/master/content-script.js)
> 
> // Listen for messages from background script
>   browser.runtime.onMessage.addListener((message) => {
>     if (message.action === "applyStyles") {
>       updateStyles(message.css);
>       return Promise.resolve({ success: true });
>     }
>     return false;
>   });
> 
> , I would expect that Firefox also notifies your extension when iframes apply their styles, right?
> 
> Maybe I am missing something... do you know of a site that had a similar case, such that I can use it as reference?

Ohhh if there are iframes, there is no way of injecting css... Don't think even js can do that... So this issue will be closed. This is very similar to the behavior of most ms office or 365 or whatever they call them... This is why in the darkreader addon, instead of applying the custom dark themed colors, it just flips colors of the iframe because that's the best we can do from the outside.

**Comment by 0qln** [comment]
It's just a small part of the page tho, so I would like to style the rest of the page. 

Is that alright?

**Comment by 0qln** [comment]
@sameerasw 

Are you sure inverting the contents of the iframe is the best we can do? For example in (this issue)[https://github.com/darkreader/darkreader/issues/5082] it does sound like we can not only inject extension code into iframes, but even send cross origin change requests.

**Comment by sameerasw** [comment]
> [@sameerasw](https://github.com/sameerasw)
> 
> Are you sure inverting the contents of the iframe is the best we can do? For example in [this issue](https://github.com/darkreader/darkreader/issues/5082) it does sound like we can not only inject extension code into iframes, but even send cross origin change requests.

I'm not familiar with same domain iframes. What darkreader does when it finds an iframe is that it only flips the color of the iframe itself... Nothing inside since it can not reliably inject it.. Also I think darkreader rely on js for injection rather than having a user stylesheet. So chance of just css reaching that level is impossible. Same thing with shadow root too but I think there's a workaround for shadow root which I'm not familiar with.

**Comment by sameerasw** [comment]
> It's just a small part of the page tho, so I would like to style the rest of the page.
> 
> Is that alright?

Ohhh I thought it was everything below the header like other pages, then it would be possible, I'll re-open :)

**Comment by 0qln** [comment]
> > It's just a small part of the page tho, so I would like to style the rest of the page.
> > Is that alright?
> 
> Ohhh I thought it was everything below the header like other pages, then it would be possible, I'll re-open :)

Thank you 😊

**Comment by 0qln** [comment]
> > [@sameerasw](https://github.com/sameerasw)
> > Are you sure inverting the contents of the iframe is the best we can do? For example in [this issue](https://github.com/darkreader/darkreader/issues/5082) it does sound like we can not only inject extension code into iframes, but even send cross origin change requests.
> 
> I'm not familiar with same domain iframes. What darkreader does when it finds an iframe is that it only flips the color of the iframe itself... Nothing inside since it can not reliably inject it.. Also I think darkreader rely on js for injection rather than having a user stylesheet. So chance of just css reaching that level is impossible. Same thing with shadow root too but I think there's a workaround for shadow root which I'm not familiar with.

First I was thinking that we would need to change the content-script.js of the plugin to also inject when iframes are loaded. Something like this `iframe.addEventListener('load', () => {...})` (which would fail for cross site iframes).

But tbh, it might just work if you specify [`allframes: true`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts) in your `manifest.json`. I will have a closer look at that tomorrow :)

The developers would then just need to target the `src` of their iframe that they want  to style with a separate website.css (like I tried above).

**Comment by 0qln** [comment]
@sameerasw updating the manifest actually did the job: https://github.com/sameerasw/zeninternet/pull/19 😁

**Comment by sameerasw** [comment]
> [@sameerasw](https://github.com/sameerasw) updating the manifest actually did the job: [sameerasw/zeninternet#19](https://github.com/sameerasw/zeninternet/pull/19) 😁

I tried with it but were you able to achieve transparency inside iframes there? Any special way to inject css? I tried with google calendar/ tasks and did not work.. Maybe there's some restrictions...

**Comment by sameerasw** [comment]
Done in #923

**Comment by 0qln** [comment]
> > [@sameerasw](https://github.com/sameerasw) updating the manifest actually did the job: [sameerasw/zeninternet#19](https://github.com/sameerasw/zeninternet/pull/19) 😁
> 
> I tried with it but were you able to achieve transparency inside iframes there? Any special way to inject css? I tried with google calendar/ tasks and did not work.. Maybe there's some restrictions...
> 
> Update: I made the iframes branch there experimenting, I was able to achieve css injection for google calendar but ended up helpless because it seems like the iframe by default have a white bg that can not be removed ;(

It least it is possible for the iframes that I tried...

Default extension:

![Image](https://github.com/user-attachments/assets/15001ea1-b28c-4486-ab39-37ac90e9bd5a)

With updated extension:

![Image](https://github.com/user-attachments/assets/cb237529-d1c4-4f20-8157-a4c03ef81249)

Can you maybe share which website you tried to style? Maybe you missed some element?

**Comment by 0qln** [comment]
I also had no problem getting the google calendar iframe to work 🤔:

![Image](https://github.com/user-attachments/assets/c972ad59-79ff-4132-8f02-de0b5bc555d7)

**Comment by sameerasw** [comment]
> I also had no problem getting the google calendar iframe to work 🤔:
> 
> ![Image](https://github.com/user-attachments/assets/c972ad59-79ff-4132-8f02-de0b5bc555d7)

It's the Task iframe in google calendar that couldn't get to work for me...

**Comment by 0qln** [comment]
Oh that's what you mean. The css dev tools don't show me exactly which css rule it is (Firefox bug? XD) But If I delete this stylesheet:

![Image](https://github.com/user-attachments/assets/8d594c62-9608-4b0f-b8e8-43aeef6eade8)

, the iframe is not white anymore. So i think this is just a specific google calendar thingy, not the general behaviour.
